import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { demoCatalog } from "@/demos/catalog";
import { SiteHeader } from "@/components/site/site-header";
import { SITE_URL, REPO_URL } from "@/lib/site-config";

const Home: NextPage = () => {
  return (
    <div className="min-h-dvh bg-background text-foreground">
      <Head>
        <title>
          remocn demos — AI-generated videos, installable with shadcn
        </title>
        <meta
          name="description"
          content="A gallery of motion design videos generated by AI agents with remocn and Remotion. Install any demo into your project with one shadcn command."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href={SITE_URL} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="remocn demos" />
        <meta property="og:url" content={SITE_URL} />
        <meta
          property="og:title"
          content="remocn demos — AI-generated videos, installable with shadcn"
        />
        <meta
          property="og:description"
          content="A gallery of motion design videos generated by AI agents with remocn and Remotion. Install any demo with one shadcn command."
        />
        <meta
          property="og:image"
          content={`${SITE_URL}/og/introducing-remocn.png`}
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>

      <SiteHeader />

      <main>
        {/* Hero */}
        <section className="pt-16 pb-12 sm:pt-24">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <p className="font-mono text-sm tracking-wide text-muted-foreground uppercase">
              Prompt in, video out
            </p>
            <h1 className="mt-3 max-w-[24ch] text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
              Videos made by AI, built with remocn.
            </h1>
            <p className="mt-5 max-w-[56ch] text-lg text-pretty text-muted-foreground">
              Every video in this gallery was generated by an AI agent from a
              single prompt — real React components, rendered with Remotion.
              Each page shows the prompt, the code, and a one-command install
              for your own project.
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-3">
              <a
                href="https://remocn.dev"
                target="_blank"
                rel="noreferrer"
                className="rounded-md bg-primary px-3 py-2 text-base font-medium text-primary-foreground hover:bg-primary/90 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary sm:text-sm"
              >
                Get remocn
              </a>
              <a
                href={REPO_URL}
                target="_blank"
                rel="noreferrer"
                className="rounded-md px-3 py-2 text-base font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground sm:text-sm"
              >
                Star on GitHub
              </a>
            </div>
          </div>
        </section>

        {/* Demo grid */}
        <section className="pb-24">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <ul
              role="list"
              className="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3"
            >
              {demoCatalog.map((demo) => (
                <li key={demo.id}>
                  <Link href={`/demo/${demo.id}`} className="group block">
                    <div className="overflow-hidden rounded-xl outline-1 -outline-offset-1 outline-black/10 dark:outline-white/10">
                      <Image
                        src={`/thumbnails/${demo.id}.png`}
                        alt=""
                        width={640}
                        height={360}
                        className="aspect-video w-full object-cover group-hover:opacity-90"
                      />
                    </div>
                    <h2 className="mt-3 text-base font-medium sm:text-sm">
                      {demo.title}
                    </h2>
                    <p className="mt-1 line-clamp-2 text-base/6 text-muted-foreground sm:text-sm/5">
                      {demo.description}
                    </p>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>
      </main>

      <footer className="border-t border-border/60 py-8">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 sm:px-6">
          <p className="text-base text-muted-foreground sm:text-sm">
            Built with{" "}
            <a
              href="https://remocn.dev"
              target="_blank"
              rel="noreferrer"
              className="font-medium text-foreground hover:underline"
            >
              remocn
            </a>{" "}
            and Remotion
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Home;
