// Representative frame per demo, shared by generate-thumbnails.mjs and
// generate-og.mjs. Defaults to the demo's mid frame; override where the mid
// frame lands on a dark cut. Refresh against `npx remotion compositions`
// when durations change.
export const FRAMES = {
  "shadcn-aria-opus": 868,
  "shadcn-react-aria": 566,
  "sponsor-reui": 100,
  "llms-txt": 450,
  "llms-txt-variants": 112,
  "remocn-ui": 580,
  "introducing-nextjs": 260,
  "introducing-vercel": 240,
  "introducing-shadcn-typeset": 620,
  "introducing-videorc": 690,
  "remocn-icons": 455,
  "remocn-icons-3d": 1285,
  "remocn-icons-onetake": 340,
  "remocn-new-logo": 300,
  "sponsor-canadian-ai": 470,
  "introducing-tenkit": 182,
  "sponsor-shadcn-ui-kit": 112,
  "sponsor-gramotion": 110,
  "shieldcn-plus": 500,
  "introducing-shadcn": 1089,
  "sponsor-orcdev": 241,
  "sponsor-reactbits": 193,
  "new-transitions": 300,
  "introducing-remocn": 506,
  "sponsor-shieldcn": 208,
  "paper-shaders": 492,
  "shieldcn": 612,
  "sponsor-ln": 99,
  "shadcn-ui": 454,
  "skill-changelog": 312,
  "tegami": 747,
  "fonttrio": 372,
  "render-sdk": 309,
  "agent-skills": 700,
  "typography": 408,
  "perf-guards": 330,
  "batchwork": 240,
  "chat-changelog": 346,
  "changelog": 240,
  "signup-flow": 115,
};
